language: java

script: "./gradlew dist"

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

deploy:
  provider: releases
  api_key:
    secure: ZYjUvIhS0pYXub02pIExbrNyUbi8K+HGetxe9KdM80AbE6XvrNo42GjBoxd85G2hH1fR8gEt+Muflnw5PPuHqzEvCCcTBxwyuRYQxtPSVu/XuGU776/vjeFlsDtLHDsLCmONq4GjV3bBaVppoJ0ElJLr/jbUD4L+C40IL2qwjfg=
  file: build/distributions/xmlcalabash1-ditaa-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
